export const optionsPaises = [
    { index: 0, value: 'AF', label: 'Afeganistão' },
    { index: 1, value: 'AL', label: 'Albânia' },
    { index: 2, value: 'DZ', label: 'Argélia' },
    { index: 3, value: 'AD', label: 'Andorra' },
    { index: 4, value: 'AO', label: 'Angola' },
    { index: 5, value: 'AG', label: 'Antígua e Barbuda' },
    { index: 6, value: 'AR', label: 'Argentina' },
    { index: 7, value: 'AM', label: 'Armênia' },
    { index: 8, value: 'AU', label: 'Austrália' },
    { index: 9, value: 'AT', label: 'Áustria' },
    { index: 10, value: 'AZ', label: 'Azerbaijão' },
    { index: 11, value: 'BS', label: 'Bahamas' },
    { index: 12, value: 'BH', label: 'Bahrein' },
    { index: 13, value: 'BD', label: 'Bangladesh' },
    { index: 14, value: 'BB', label: 'Barbados' },
    { index: 15, value: 'BY', label: 'Belarus' },
    { index: 16, value: 'BE', label: 'Bélgica' },
    { index: 17, value: 'BZ', label: 'Belize' },
    { index: 18, value: 'BJ', label: 'Benin' },
    { index: 19, value: 'BT', label: 'Butão' },
    { index: 20, value: 'BO', label: 'Bolívia' },
    { index: 21, value: 'BA', label: 'Bósnia e Herzegovina' },
    { index: 22, value: 'BW', label: 'Botsuana' },
    { index: 23, value: 'BR', label: 'Brasil' },
    { index: 24, value: 'BN', label: 'Brunei' },
    { index: 25, value: 'BG', label: 'Bulgária' },
    { index: 26, value: 'BF', label: 'Burkina Faso' },
    { index: 27, value: 'BI', label: 'Burundi' },
    { index: 28, value: 'KH', label: 'Camboja' },
    { index: 29, value: 'CM', label: 'Camarões' },
    { index: 30, value: 'CA', label: 'Canadá' },
    { index: 31, value: 'CV', label: 'Cabo Verde' },
    { index: 32, value: 'CF', label: 'República Centro-Africana' },
    { index: 33, value: 'TD', label: 'Chade' },
    { index: 34, value: 'CL', label: 'Chile' },
    { index: 35, value: 'CN', label: 'China' },
    { index: 36, value: 'CO', label: 'Colômbia' },
    { index: 37, value: 'KM', label: 'Comores' },
    { index: 38, value: 'CG', label: 'República do Congo' },
    { index: 39, value: 'CD', label: 'República Democrática do Congo' },
    { index: 40, value: 'CR', label: 'Costa Rica' },
    { index: 41, value: 'HR', label: 'Croácia' },
    { index: 42, value: 'CU', label: 'Cuba' },
    { index: 43, value: 'CY', label: 'Chipre' },
    { index: 44, value: 'CZ', label: 'República Tcheca' },
    { index: 45, value: 'DK', label: 'Dinamarca' },
    { index: 46, value: 'DJ', label: 'Djibuti' },
    { index: 47, value: 'DM', label: 'Dominica' },
    { index: 48, value: 'DO', label: 'República Dominicana' },
    { index: 49, value: 'EC', label: 'Equador' },
    { index: 50, value: 'EG', label: 'Egito' },
    { index: 51, value: 'SV', label: 'El Salvador' },
    { index: 52, value: 'GQ', label: 'Guiné Equatorial' },
    { index: 53, value: 'ER', label: 'Eritreia' },
    { index: 54, value: 'EE', label: 'Estônia' },
    { index: 55, value: 'ET', label: 'Etiópia' },
    { index: 56, value: 'FJ', label: 'Fiji' },
    { index: 57, value: 'FI', label: 'Finlândia' },
    { index: 58, value: 'FR', label: 'França' },
    { index: 59, value: 'GA', label: 'Gabão' },
    { index: 60, value: 'GM', label: 'Gâmbia' },
    { index: 61, value: 'GE', label: 'Geórgia' },
    { index: 62, value: 'DE', label: 'Alemanha' },
    { index: 63, value: 'GH', label: 'Gana' },
    { index: 64, value: 'GR', label: 'Grécia' },
    { index: 65, value: 'GD', label: 'Granada' },
    { index: 66, value: 'GT', label: 'Guatemala' },
    { index: 67, value: 'GN', label: 'Guiné' },
    { index: 68, value: 'GW', label: 'Guiné-Bissau' },
    { index: 69, value: 'GY', label: 'Guiana' },
    { index: 70, value: 'HT', label: 'Haiti' },
    { index: 71, value: 'HN', label: 'Honduras' },
    { index: 72, value: 'HU', label: 'Hungria' },
    { index: 73, value: 'IS', label: 'Islândia' },
    { index: 74, value: 'IN', label: 'Índia' },
    { index: 75, value: 'ID', label: 'Indonésia' },
    { index: 76, value: 'IR', label: 'Irã' },
    { index: 77, value: 'IQ', label: 'Iraque' },
    { index: 78, value: 'IE', label: 'Irlanda' },
    { index: 79, value: 'IL', label: 'Israel' },
    { index: 80, value: 'IT', label: 'Itália' },
    { index: 81, value: 'JM', label: 'Jamaica' },
    { index: 82, value: 'JP', label: 'Japão' },
    { index: 83, value: 'JO', label: 'Jordânia' },
    { index: 84, value: 'KZ', label: 'Cazaquistão' },
    { index: 85, value: 'KE', label: 'Quênia' },
    { index: 86, value: 'KI', label: 'Quiribati' },
    { index: 87, value: 'KW', label: 'Kuwait' },
    { index: 88, value: 'KG', label: 'Quirguistão' },
    { index: 89, value: 'LA', label: 'Laos' },
    { index: 90, value: 'LV', label: 'Letônia' },
    { index: 91, value: 'LB', label: 'Líbano' },
    { index: 92, value: 'LS', label: 'Lesoto' },
    { index: 93, value: 'LR', label: 'Libéria' },
    { index: 94, value: 'LY', label: 'Líbia' },
    { index: 95, value: 'LI', label: 'Liechtenstein' },
    { index: 96, value: 'LT', label: 'Lituânia' },
    { index: 97, value: 'LU', label: 'Luxemburgo' },
    { index: 98, value: 'MG', label: 'Madagascar' },
    { index: 99, value: 'MW', label: 'Malaui' },
    { index: 100, value: 'MY', label: 'Malásia' },
    { index: 101, value: 'MV', label: 'Maldivas' },
    { index: 102, value: 'ML', label: 'Mali' },
    { index: 103, value: 'MT', label: 'Malta' },
    { index: 104, value: 'MH', label: 'Ilhas Marshall' },
    { index: 105, value: 'MR', label: 'Mauritânia' },
    { index: 106, value: 'MU', label: 'Maurício' },
    { index: 107, value: 'MX', label: 'México' },
    { index: 108, value: 'FM', label: 'Micronésia' },
    { index: 109, value: 'MD', label: 'Moldávia' },
    { index: 110, value: 'MC', label: 'Mônaco' },
    { index: 111, value: 'MN', label: 'Mongólia' },
    { index: 112, value: 'ME', label: 'Montenegro' },
    { index: 113, value: 'MA', label: 'Marrocos' },
    { index: 114, value: 'MZ', label: 'Moçambique' },
    { index: 115, value: 'MM', label: 'Myanmar' },
    { index: 116, value: 'NA', label: 'Namíbia' },
    { index: 117, value: 'NR', label: 'Nauru' },
    { index: 118, value: 'NP', label: 'Nepal' },
    { index: 119, value: 'NL', label: 'Países Baixos' },
    { index: 120, value: 'NZ', label: 'Nova Zelândia' },
    { index: 121, value: 'NI', label: 'Nicarágua' },
    { index: 122, value: 'NE', label: 'Níger' },
    { index: 123, value: 'NG', label: 'Nigéria' },
    { index: 124, value: 'NO', label: 'Noruega' },
    { index: 125, value: 'OM', label: 'Omã' },
    { index: 126, value: 'PK', label: 'Paquistão' },
    { index: 127, value: 'PW', label: 'Palau' },
    { index: 128, value: 'PS', label: 'Palestina' },
    { index: 129, value: 'PA', label: 'Panamá' },
    { index: 130, value: 'PG', label: 'Papua Nova Guiné' },
    { index: 131, value: 'PY', label: 'Paraguai' },
    { index: 132, value: 'PE', label: 'Peru' },
    { index: 133, value: 'PH', label: 'Filipinas' },
    { index: 134, value: 'PL', label: 'Polônia' },
    { index: 135, value: 'PT', label: 'Portugal' },
    { index: 136, value: 'QA', label: 'Catar' },
    { index: 137, value: 'RO', label: 'Romênia' },
    { index: 138, value: 'RU', label: 'Rússia' },
    { index: 139, value: 'RW', label: 'Ruanda' },
    { index: 140, value: 'KN', label: 'São Cristóvão e Nevis' },
    { index: 141, value: 'LC', label: 'Santa Lúcia' },
    { index: 142, value: 'VC', label: 'São Vicente e Granadinas' },
    { index: 143, value: 'WS', label: 'Samoa' },
    { index: 144, value: 'SM', label: 'San Marino' },
    { index: 145, value: 'ST', label: 'São Tomé e Príncipe' },
    { index: 146, value: 'SA', label: 'Arábia Saudita' },
    { index: 147, value: 'SN', label: 'Senegal' },
    { index: 148, value: 'RS', label: 'Sérvia' },
    { index: 149, value: 'SC', label: 'Seychelles' },
    { index: 150, value: 'SL', label: 'Serra Leoa' },
    { index: 151, value: 'SG', label: 'Singapura' },
    { index: 152, value: 'SK', label: 'Eslováquia' },
    { index: 153, value: 'SI', label: 'Eslovênia' },
    { index: 154, value: 'SB', label: 'Ilhas Salomão' },
    { index: 155, value: 'SO', label: 'Somália' },
    { index: 156, value: 'ZA', label: 'África do Sul' },
    { index: 157, value: 'KR', label: 'Coreia do Sul' },
    { index: 158, value: 'SS', label: 'Sudão do Sul' },
    { index: 159, value: 'ES', label: 'Espanha' },
    { index: 160, value: 'LK', label: 'Sri Lanka' },
    { index: 161, value: 'SD', label: 'Sudão' },
    { index: 162, value: 'SR', label: 'Suriname' },
    { index: 163, value: 'SZ', label: 'Suazilândia' },
    { index: 164, value: 'SE', label: 'Suécia' },
    { index: 165, value: 'CH', label: 'Suíça' },
    { index: 166, value: 'SY', label: 'Síria' },
    { index: 167, value: 'TJ', label: 'Tajiquistão' },
    { index: 168, value: 'TZ', label: 'Tanzânia' },
    { index: 169, value: 'TH', label: 'Tailândia' },
    { index: 170, value: 'TL', label: 'Timor-Leste' },
    { index: 171, value: 'TG', label: 'Togo' },
  
  
    { index: 172, value: 'TO', label: 'Tonga' },
    { index: 173, value: 'TT', label: 'Trinidad e Tobago' },
    { index: 174, value: 'TN', label: 'Tunísia' },
    { index: 175, value: 'TR', label: 'Turquia' },
    { index: 176, value: 'TM', label: 'Turcomenistão' },
    { index: 177, value: 'TV', label: 'Tuvalu' },
    { index: 178, value: 'UG', label: 'Uganda' },
    { index: 179, value: 'UA', label: 'Ucrânia' },
    { index: 180, value: 'AE', label: 'Emirados Árabes Unidos' },
    { index: 181, value: 'GB', label: 'Reino Unido' },
    { index: 182, value: 'US', label: 'Estados Unidos' },
    { index: 183, value: 'UY', label: 'Uruguai' },
    { index: 184, value: 'UZ', label: 'Uzbequistão' },
    { index: 185, value: 'VU', label: 'Vanuatu' },
    { index: 186, value: 'VA', label: 'Vaticano' },
    { index: 187, value: 'VE', label: 'Venezuela' },
    { index: 188, value: 'VN', label: 'Vietnã' },
    { index: 189, value: 'YE', label: 'Iêmen' },
    { index: 190, value: 'ZM', label: 'Zâmbia' },
    { index: 191, value: 'ZW', label: 'Zimbábue' }
  ]
  